### ISSUE TITLE
Broken link in footer

### ISSUE THREAD

**Issue by jbampton** [Andrew-Colman/image-fetch#26]
I know there is the `a` HTML tag and also the React `Link` tag.  

<img width="840" alt="Screen Shot 2020-12-31 at 4 19 08 pm" src="https://user-images.githubusercontent.com/418747/103397458-3876ad00-4b84-11eb-960e-91ee22d1b2ad.png">

<img width="250" alt="Screen Shot 2020-12-31 at 4 21 38 pm" src="https://user-images.githubusercontent.com/418747/103397484-4cbaaa00-4b84-11eb-9686-028574cbfaa4.png">

**Comment by Andrew-Colman** [comment]
fixed by https://github.com/Andrew-Colman/image-fetch/commit/70ffc037ae47d020adf49ce5e470c3ec70e6d75e
